### ISSUE TITLE
YubiHSM Support

### ISSUE THREAD

**Issue by the-w-spears** [eclipse-keypont/crypto11#23]
I'm trying to get this up and running to communicate with a YubiHSM2 via https://developers.yubico.com/YubiHSM2/Component_Reference/PKCS_11/ but, the test always fails with a panic. 

exact error output is here: 
```
2019/01/18 11:20:47 Failed to initialize PKCS#11 library: pkcs11: 0x6: CKR_FUNCTION_FAILED
--- FAIL: TestClose (0.00s)
    close_test.go:36: pkcs11: 0x6: CKR_FUNCTION_FAILED
2019/01/18 11:20:47 PKCS#11 library already configured
2019/01/18 11:20:47 PKCS#11 library already configured
2019/01/18 11:20:47 PKCS#11 library already configured
2019/01/18 11:20:47 PKCS#11 library already configured
--- FAIL: TestLoginContext (0.00s)
    --- FAIL: TestLoginContext/key_identity_with_login (0.00s)
        crypto11_test.go:57: crypto11.GenerateDSAKeyPair: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
    --- FAIL: TestLoginContext/key_identity_with_expiration (0.00s)
        crypto11_test.go:100: crypto11.GenerateDSAKeyPair: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
    --- FAIL: TestLoginContext/login_context_shared_between_sessions (0.00s)
        crypto11_test.go:134: crypto11.GenerateDSAKeyPair: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
2019/01/18 11:20:47 PKCS#11 library already configured
--- FAIL: TestIdentityExpiration (0.00s)
    crypto11_test.go:178: crypto11.GenerateDSAKeyPair: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
2019/01/18 11:20:47 PKCS#11 library already configured
--- FAIL: TestHardDSA (0.00s)
    dsa_test.go:109: crypto11.GenerateDSAKeyPair: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
2019/01/18 11:20:47 PKCS#11 library already configured
--- FAIL: TestHardECDSA (0.00s)
    ecdsa_test.go:67: GenerateECDSAKeyPair: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
2019/01/18 11:20:47 PKCS#11 library already configured
--- FAIL: TestHmac (0.00s)
    hmac_test.go:36: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
2019/01/18 11:20:47 PKCS#11 library already configured
2019/01/18 11:20:48 PKCS#11 library already configured
2019/01/18 11:20:48 PKCS#11 library already configured
2019/01/18 11:20:50 PKCS#11 library already configured
--- FAIL: TestPoolTimeout (3.01s)
    --- FAIL: TestPoolTimeout/first_login,_exp_0s (1.00s)
        pool_test.go:51: failed to generate a key, unexpected error: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
    --- FAIL: TestPoolTimeout/reuse_expired_handle,_exp_0s (0.00s)
        pool_test.go:66: failed to generate a key: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
    --- FAIL: TestPoolTimeout/first_login,_exp_1s (2.00s)
        pool_test.go:51: failed to generate a key, unexpected error: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
    --- FAIL: TestPoolTimeout/reuse_expired_handle,_exp_1s (0.00s)
        pool_test.go:66: failed to generate a key: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
2019/01/18 11:20:50 PKCS#11 library already configured
--- FAIL: TestRandomReader (0.00s)
    rand_test.go:36: crypto11.PKCS11RandRead.Read: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
2019/01/18 11:20:50 PKCS#11 library already configured
--- FAIL: TestNativeRSA (0.13s)
    --- FAIL: TestNativeRSA/1024 (0.02s)
        --- FAIL: TestNativeRSA/1024/Encrypt (0.00s)
            --- FAIL: TestNativeRSA/1024/Encrypt/OAEPSHA1 (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/1024/Encrypt/OAEPSHA224 (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/1024/Encrypt/OAEPSHA256 (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/1024/Encrypt/OAEPSHA384 (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/1024/Encrypt/OAEPSHA1Label (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/1024/Encrypt/OAEPSHA224Label (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/1024/Encrypt/OAEPSHA256Label (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/1024/Encrypt/OAEPSHA384Label (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
    --- FAIL: TestNativeRSA/2048 (0.11s)
        --- FAIL: TestNativeRSA/2048/Encrypt (0.00s)
            --- FAIL: TestNativeRSA/2048/Encrypt/OAEPSHA1 (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/2048/Encrypt/OAEPSHA224 (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/2048/Encrypt/OAEPSHA256 (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/2048/Encrypt/OAEPSHA384 (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/2048/Encrypt/OAEPSHA512 (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/2048/Encrypt/OAEPSHA1Label (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/2048/Encrypt/OAEPSHA224Label (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/2048/Encrypt/OAEPSHA256Label (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/2048/Encrypt/OAEPSHA384Label (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/2048/Encrypt/OAEPSHA512Label (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
2019/01/18 11:20:50 PKCS#11 library already configured
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x590c1b]

goroutine 100 [running]:
testing.tRunner.func1(0xc000386300)
	/usr/local/go/src/testing/testing.go:792 +0x387
panic(0x5cb280, 0x951b40)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/thalesignite/crypto11.TestHardRSA.func1.2(0xc000386300)
	/home/wspears/go/src/github.com/thalesignite/crypto11/rsa_test.go:84 +0x2b
testing.tRunner(0xc000386300, 0xc0003d4120)
	/usr/local/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x353
exit status 2
FAIL	github.com/thalesignite/crypto11	3.424s
```

Ideas? Or pointers in the right direction?

**Comment by dmjones** [comment]
As a wild guess, I'm wondering if your configuration is correct. Did you edit the `config` file appropriately?

I've noticed the tests ignore a lot of errors. I'm going to fix this and push a new change. I'll ping you once that's done and perhaps re-running the tests will provide some more insight.

**Comment by dmjones** [comment]
@the-w-spears - I've updated master so that the unit tests correctly examine errors. Can you please try again and see what happens?

**Comment by the-w-spears** [comment]
Sure! sorry for the delay, for some reason I wasn't getting email from github. 
Here is the new error message after go get -u 

```
2019/01/28 10:17:05 Failed to initialize PKCS#11 library: pkcs11: 0x6: CKR_FUNCTION_FAILED
--- FAIL: TestClose (0.01s)
    close_test.go:36: pkcs11: 0x6: CKR_FUNCTION_FAILED
2019/01/28 10:17:05 PKCS#11 library already configured
2019/01/28 10:17:05 PKCS#11 library already configured
2019/01/28 10:17:05 PKCS#11 library already configured
2019/01/28 10:17:05 PKCS#11 library already configured
--- FAIL: TestLoginContext (0.00s)
    --- FAIL: TestLoginContext/key_identity_with_login (0.00s)
        crypto11_test.go:57: crypto11.GenerateDSAKeyPair: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
    --- FAIL: TestLoginContext/key_identity_with_expiration (0.00s)
        crypto11_test.go:100: crypto11.GenerateDSAKeyPair: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
    --- FAIL: TestLoginContext/login_context_shared_between_sessions (0.00s)
        crypto11_test.go:134: crypto11.GenerateDSAKeyPair: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
2019/01/28 10:17:05 PKCS#11 library already configured
--- FAIL: TestIdentityExpiration (0.00s)
    crypto11_test.go:178: crypto11.GenerateDSAKeyPair: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
2019/01/28 10:17:05 PKCS#11 library already configured
--- FAIL: TestHardDSA (0.00s)
    dsa_test.go:109: crypto11.GenerateDSAKeyPair: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
2019/01/28 10:17:06 PKCS#11 library already configured
--- FAIL: TestHardECDSA (0.00s)
    ecdsa_test.go:67: GenerateECDSAKeyPair: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
2019/01/28 10:17:06 PKCS#11 library already configured
--- FAIL: TestHmac (0.00s)
    hmac_test.go:36: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
2019/01/28 10:17:06 PKCS#11 library already configured
2019/01/28 10:17:07 PKCS#11 library already configured
2019/01/28 10:17:07 PKCS#11 library already configured
2019/01/28 10:17:09 PKCS#11 library already configured
--- FAIL: TestPoolTimeout (3.01s)
    --- FAIL: TestPoolTimeout/first_login,_exp_0s (1.00s)
        pool_test.go:51: failed to generate a key, unexpected error: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
    --- FAIL: TestPoolTimeout/reuse_expired_handle,_exp_0s (0.00s)
        pool_test.go:66: failed to generate a key: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
    --- FAIL: TestPoolTimeout/first_login,_exp_1s (2.00s)
        pool_test.go:51: failed to generate a key, unexpected error: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
    --- FAIL: TestPoolTimeout/reuse_expired_handle,_exp_1s (0.00s)
        pool_test.go:66: failed to generate a key: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
2019/01/28 10:17:09 PKCS#11 library already configured
--- FAIL: TestRandomReader (0.00s)
    rand_test.go:36: crypto11.PKCS11RandRead.Read: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
2019/01/28 10:17:09 PKCS#11 library already configured
--- FAIL: TestNativeRSA (0.48s)
    --- FAIL: TestNativeRSA/1024 (0.02s)
        --- FAIL: TestNativeRSA/1024/Encrypt (0.00s)
            --- FAIL: TestNativeRSA/1024/Encrypt/OAEPSHA1 (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/1024/Encrypt/OAEPSHA224 (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/1024/Encrypt/OAEPSHA256 (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/1024/Encrypt/OAEPSHA384 (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/1024/Encrypt/OAEPSHA1Label (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/1024/Encrypt/OAEPSHA224Label (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/1024/Encrypt/OAEPSHA256Label (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/1024/Encrypt/OAEPSHA384Label (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
    --- FAIL: TestNativeRSA/2048 (0.45s)
        --- FAIL: TestNativeRSA/2048/Encrypt (0.00s)
            --- FAIL: TestNativeRSA/2048/Encrypt/OAEPSHA1 (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/2048/Encrypt/OAEPSHA224 (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/2048/Encrypt/OAEPSHA256 (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/2048/Encrypt/OAEPSHA384 (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/2048/Encrypt/OAEPSHA512 (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/2048/Encrypt/OAEPSHA1Label (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/2048/Encrypt/OAEPSHA224Label (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/2048/Encrypt/OAEPSHA256Label (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/2048/Encrypt/OAEPSHA384Label (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
            --- FAIL: TestNativeRSA/2048/Encrypt/OAEPSHA512Label (0.00s)
                rsa_test.go:244: GetInfo: pkcs11: 0x190: CKR_CRYPTOKI_NOT_INITIALIZED
2019/01/28 10:17:09 PKCS#11 library already configured
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x590c1b]

goroutine 100 [running]:
testing.tRunner.func1(0xc000258100)
	/usr/local/go/src/testing/testing.go:792 +0x387
panic(0x5cb280, 0x951b40)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/thalesignite/crypto11.TestHardRSA.func1.2(0xc000258100)
	/home/wspears/go/src/github.com/thalesignite/crypto11/rsa_test.go:84 +0x2b
testing.tRunner(0xc000258100, 0xc00000d660)
	/usr/local/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x353
exit status 2
FAIL	github.com/thalesignite/crypto11	3.788s
```

**Comment by dmjones** [comment]
It doesn't look like you're using the latest code. I'm not sure why `go get -u` didn't work, but you can see in the log above that the line numbers don't match. In fact, they are exactly the same line numbers as your first log.

For instance, you have a test error at line 36 of `hmac_test.go`. If you look at [`hmac_test.go:36`](https://github.com/ThalesIgnite/crypto11/blob/master/hmac_test.go#L36), it's no longer a line that can throw a test assertion.

I would suggest you delete `$GOPATH/src/github.com/ThalesIgnite/crypto11/` and run `go get` again to be sure.

Before you run the tests, please make sure you have updated the `config` file, so it points at your YubiHSM PKCS#11 library file and contains the correct token name and PIN.

**Comment by dmjones** [comment]
I'm closing this issue due to a lack of response. Please comment again (or raise another issue) if you have ongoing issues.

**Comment by pbdeuchler** [comment]
FWIW, I am getting this error, however I believe the problem lies with the underlying pkcs11 library. I am not sure if that library supports pkcs11 modules, which is required for yubihsm interaction.
